apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: pyui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: rr1docker1/final-proj-app:v1
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.json
          subPath: config.json
      env:
        - name: MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mongodb_url
      volumes:
      - name: config-volume
        configMap:
          name: app-config
