
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
  namespace: pyui
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage-class
  local:
    path: /mnt/disks/local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-cluster-control-plane
