apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: pyui
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "logs_db"
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "1Gi"   # Minimum memory requested for the container
            cpu: "500m"     # Minimum CPU requested for the container
          limits:
            memory: "2Gi"   # Maximum memory the container can use
            cpu: "1"        # Maximum CPU the container can use
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi     # Moderate storage for the PersistentVolumeClaim
      storageClassName: mysql-storage-class
